name: Budgetin Back CI

on:
    push:
        branches: [ "main" ]
        paths:
          - .github/workflows/ci-back.yml
          - 'budgetin-back/**/*.kt'
          - 'budgetin-back/**/*.kts'
          - 'budgetin-back/gradle.properties'
          - 'budgetin-back/gradle/**'
    pull_request:
        branches: [ "**" ]
        paths:
          - .github/workflows/ci-back.yml
          - 'budgetin-back/**/*.kt'
          - 'budgetin-back/**/*.kts'
          - 'budgetin-back/gradle.properties'
          - 'budgetin-back/gradle/**'

permissions:
    contents: read

jobs:
    build:

        concurrency: budgetin-back-ci

        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: budgetin-back

        steps:
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                    java-version: '17'
                    distribution: 'temurin'

            - name: Checkout IZIVIA OCPI toolkit library code from GH
              uses: actions/checkout@v4

            - name: Setup gradle action
              uses: gradle/gradle-build-action@v2.10.0
              with:
                  gradle-version: wrapper
                  cache-read-only: ${{ github.ref != 'refs/heads/main' }}
                  gradle-home-cache-cleanup: true

            - name: Ktlint check
              run: ./gradlew ktlintCheck

            - name: Build
              run: ./gradlew build
