name: Budgetin Front CI

on:
    push:
        branches: [ "main" ]
        paths:
          - .github/workflows/ci-front.yml
          - '../../budgetin-front/**'
    pull_request:
        branches: [ "**" ]
        paths:
          - .github/workflows/ci-front.yml
          - '../../budgetin-front/**'

permissions:
    contents: read

jobs:
    build:

        concurrency: budgetin-front-ci

        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: budgetin-front

        steps:
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            - name: Checkout IZIVIA OCPI toolkit library code from GH
              uses: actions/checkout@v4

            - name: Install
              run: npm ci
            - name: Lint check
              run: npm run lint
            - name: Format check
              run: npm run format
            - name: Build
              run: npm run build --if-present
