name: Dasbod Front CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "**" ]

permissions:
    contents: read

jobs:
    build:

        concurrency: dasbod-front-ci

        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: dasbod-front

        steps:
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '17.x'

            - name: Checkout IZIVIA OCPI toolkit library code from GH
              uses: actions/checkout@v4

            - name: Install
              run: npm ci
            - name: Build
              run: npm run build --if-present
