name: Dasbod Front CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "**" ]

permissions:
    contents: read

jobs:
    build:

        concurrency: dasbod-front-ci

        runs-on: ubuntu-latest

        steps:
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '17.x'

            - name: Checkout IZIVIA OCPI toolkit library code from GH
              uses: actions/checkout@v4

            - name: Change directory
              run: cd dasbod-front

            - run: npm ci
            - run: npm run build --if-present
